Return-Path: <linux-crypto-owner@vger.kernel.org>
X-Original-To: lists+linux-crypto@lfdr.de
Delivered-To: lists+linux-crypto@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [23.128.96.18])
	by mail.lfdr.de (Postfix) with ESMTP id 814ED479AFC
	for <lists+linux-crypto@lfdr.de>; Sat, 18 Dec 2021 14:27:08 +0100 (CET)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S233147AbhLRN0q (ORCPT <rfc822;lists+linux-crypto@lfdr.de>);
        Sat, 18 Dec 2021 08:26:46 -0500
Received: from mga01.intel.com ([192.55.52.88]:38953 "EHLO mga01.intel.com"
        rhost-flags-OK-OK-OK-OK) by vger.kernel.org with ESMTP
        id S233111AbhLRN0q (ORCPT <rfc822;linux-crypto@vger.kernel.org>);
        Sat, 18 Dec 2021 08:26:46 -0500
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple;
  d=intel.com; i=@intel.com; q=dns/txt; s=Intel;
  t=1639834006; x=1671370006;
  h=date:from:to:cc:subject:message-id:mime-version;
  bh=Xu4gHmGIbEVw9JzCHr9PqnAgZ2d2nKSN3y4IC8HgOBY=;
  b=Qf4VYGbGAigOgDQ20y3KuT2TC5+gb5vM6WSfCq2thxBRj66s+8X7hOYH
   DjbwLMN5aqER7x8UOpSISvUmnRk0y8yQF7rGV+ynOWnahcrMNfNiyecG3
   zv1/JD6KTnHVHboLGdvtOUmLtfIAfKSbpFdEh6s6AB/mgd352fX21VIW5
   bJ2yO3kLRsjGoNLzQJ1sfyXwMNZwsqmogJdUHhcajjSLLOIiry2TrV09K
   39ymTJdDf96o9kN7kqy+UjNdUnENShoKtkWqsM8a7NYvlVS97V3hzEqlL
   MWpDgFwsAYVQXN+OUiQtr/LTp17lujLjItOhZWIh19Q3PLp7PVaQ64K6l
   Q==;
X-IronPort-AV: E=McAfee;i="6200,9189,10201"; a="264103493"
X-IronPort-AV: E=Sophos;i="5.88,216,1635231600"; 
   d="scan'208";a="264103493"
Received: from fmsmga006.fm.intel.com ([10.253.24.20])
  by fmsmga101.fm.intel.com with ESMTP/TLS/ECDHE-RSA-AES256-GCM-SHA384; 18 Dec 2021 05:26:46 -0800
X-ExtLoop1: 1
X-IronPort-AV: E=Sophos;i="5.88,216,1635231600"; 
   d="scan'208";a="754862745"
Received: from lkp-server02.sh.intel.com (HELO 9f38c0981d9f) ([10.239.97.151])
  by fmsmga006.fm.intel.com with ESMTP; 18 Dec 2021 05:26:44 -0800
Received: from kbuild by 9f38c0981d9f with local (Exim 4.92)
        (envelope-from <lkp@intel.com>)
        id 1myZjY-00061x-3f; Sat, 18 Dec 2021 13:26:44 +0000
Date:   Sat, 18 Dec 2021 21:25:42 +0800
From:   kernel test robot <lkp@intel.com>
To:     David Rientjes <rientjes@google.com>
Cc:     kbuild-all@lists.01.org, linux-crypto@vger.kernel.org,
        Herbert Xu <herbert@gondor.apana.org.au>,
        Peter Gonda <pgonda@google.com>, Marc Orr <marcorr@google.com>
Subject: [PATCH] crypto: fix semicolon.cocci warnings
Message-ID: <20211218132541.GA80986@65b4fbea3a32>
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Disposition: inline
X-Patchwork-Hint: ignore
User-Agent: Mutt/1.10.1 (2018-07-13)
Precedence: bulk
List-ID: <linux-crypto.vger.kernel.org>
X-Mailing-List: linux-crypto@vger.kernel.org

From: kernel test robot <lkp@intel.com>

drivers/crypto/ccp/sev-dev.c:263:2-3: Unneeded semicolon


 Remove unneeded semicolon.

Generated by: scripts/coccinelle/misc/semicolon.cocci

Fixes: 3d725965f836 ("crypto: ccp - Add SEV_INIT_EX support")
CC: David Rientjes <rientjes@google.com>
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: kernel test robot <lkp@intel.com>
---

tree:   https://git.kernel.org/pub/scm/linux/kernel/git/herbert/cryptodev-2.6.git master
head:   696645d25bafd6ba3562611c29bc8ecd47066dfe
commit: 3d725965f836a7acbd1674e33644bec18373de53 [83/95] crypto: ccp - Add SEV_INIT_EX support
:::::: branch date: 31 hours ago
:::::: commit date: 31 hours ago

 sev-dev.c |    2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

--- a/drivers/crypto/ccp/sev-dev.c
+++ b/drivers/crypto/ccp/sev-dev.c
@@ -260,7 +260,7 @@ static void sev_write_init_ex_file_if_re
 		break;
 	default:
 		return;
-	};
+	}
 
 	sev_write_init_ex_file();
 }
